[package]
name = "open_ui"
version = "0.1.0"
authors = ["craig <craigfay1@gmail.com>"]
edition = "2018"
license-file = "LICENSE"


[lib]
name = "open_ui"
path = "src/lib.rs"

[features]
image_manipulation = []

[dependencies]
glium = "0.31.0"
